[env:nano33ble]
platform = nordicnrf52@10.11.0
board = nano33ble
framework = arduino
monitor_speed = 115200
build_flags = -w -Wno-cpp -DSIGNAL_BENCH_VERSION=\"0.2.0.dev0\"
lib_deps =
    spaziochirale/Chirale_TensorFLowLite@2.0.0
