# SPDX-License-Identifier: Apache-2.0
"""Regenerate launch-tier acceptance bands from the measurement database."""

from __future__ import annotations

import argparse
import statistics
import sys
from collections.abc import Sequence
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from signal_bench.synth._partial import repeat_quarantined
from signal_bench.synth.exporter import export_matrix
from signal_bench.synth.matrix_config import load_matrix_config
from signal_bench.synth.matrix_data import CellData, RunData

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DB = ROOT / "data" / "p3_mcu_matrix.db"
DEFAULT_MATRIX_CONFIG = ROOT / "configs" / "matrix.yaml"
DEFAULT_OUTPUT = ROOT / "docs" / "launch-tier-acceptance-bands.md"
DEFAULT_VARIANCE_FLOOR = 0.15
LAUNCH_TARGETS = ("f401re", "nano33", "esp32s3")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--matrix-config", type=Path, default=DEFAULT_MATRIX_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--power-source", default="ina219")
    parser.add_argument(
        "--check", action="store_true", help="Fail if --output differs from regenerated content."
    )
    args = parser.parse_args()

    content = generate_markdown(args)
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != content:
            print(f"{args.output} is out of date; rerun without --check", file=sys.stderr)
            return 1
        print(f"{args.output} matches regenerated launch-tier acceptance bands.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


def generate_markdown(args: argparse.Namespace) -> str:
    floor = DEFAULT_VARIANCE_FLOOR
    matrix_config = load_matrix_config(args.matrix_config)
    launch_cells = [cell for cell in matrix_config.cells if cell.target in LAUNCH_TARGETS]
    matrix_config = matrix_config.model_copy(update={"cells": launch_cells})
    engine = create_engine(f"sqlite:///{args.db}")
    try:
        with Session(engine) as session:
            matrix = export_matrix(
                matrix_config,
                session,
                output_path=None,
                power_source=args.power_source,
            )
    finally:
        engine.dispose()

    lines = [
        "# Launch-Tier Acceptance Bands",
        "",
        "<!-- Generated by scripts/generate_launch_tier_acceptance_bands.py; do not edit by hand. -->",
        "",
        "These bands are for reproducing the Post 1 MCU methodology on a rebuilt rig.",
        "They are not universal device specifications.",
        "",
        "Public no-hardware verification regenerates these bands from the pinned",
        "Hugging Face telemetry bundle with:",
        "",
        "```bash",
        "uv run python scripts/verify_post1_from_bundle.py",
        "```",
        "",
        "Maintainers can regenerate this committed file from the local working",
        "measurement database with:",
        "",
        "```bash",
        "uv run python scripts/generate_launch_tier_acceptance_bands.py \\",
        "  --db data/p3_mcu_matrix.db \\",
        "  --output docs/launch-tier-acceptance-bands.md",
        "```",
        "",
        "Check that the committed file matches the database-derived bands with:",
        "",
        "```bash",
        "uv run python scripts/generate_launch_tier_acceptance_bands.py \\",
        "  --db data/p3_mcu_matrix.db \\",
        "  --output docs/launch-tier-acceptance-bands.md \\",
        "  --check",
        "```",
        "",
        "Basis:",
        "",
        f"- Generated from `{_db_source_label(args.db)}` using `{_display_path(args.matrix_config)}`.",
        f"- Power source: `{args.power_source}`.",
        "- Published headline values are recomputed from the launch-tier DB rows selected by the matrix config.",
        "- The synthesis rule excludes telemetry-partial rows and rows marked `repeat stats quarantined`.",
        "- Dan-bench CV is the coefficient of variation across the accepted repeat rows.",
        f"- The rebuilt-rig acceptance band is `max(3 * Dan-bench CV, {floor:.0%})`.",
        f"- The rebuilt-rig acceptance floor is `{floor:.0%}`.",
        "",
        "Use the band as a triage rule:",
        "",
        "- Inside the band: reproduction of the launch-tier method on a comparable rig.",
        "- Outside the band: inspect wiring, boundary state, meter agreement, firmware",
        "  version, serial timing, supply path, and ambient conditions before treating the",
        "  difference as a hardware finding.",
        "",
        "| Task | Board | Energy p50 (mWh/1000) | Dan-bench energy CV | Energy band (mWh/1000) | Latency p50 (ms) | Dan-bench latency CV | Latency band (ms) |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for cell in matrix.cells:
        lines.append(_table_row(cell, floor))
    lines.extend(
        [
            "",
            "Caveat: the current matrix artifact leaves run",
            "`019e6532-b4fd-7310-8cf7-4eda7c26f834` in the ESP32-S3 AD non-partial headline",
            "set with about `0.0042 mWh/1000`, while the surrounding accepted runs are about",
            "`1.43-1.44 mWh/1000`. That row does not move the median, but it makes the",
            "raw energy CV meaningless. Until that data-hygiene defect is resolved, use the",
            "15% rebuilt-rig band around the published median for ESP32-S3 AD and treat the",
            "CV as not publishable.",
            "",
            "Different labs should expect more spread than Dan's bench. Supply noise, USB",
            "hub behavior, board revision, room temperature, and debug-interface state can",
            "all move devkit-boundary energy. The band is a launch reproducibility gate, not",
            "a promise that every nominally identical board will land there.",
            "",
        ],
    )
    return "\n".join(lines)


def _table_row(cell: CellData, floor: float) -> str:
    energy_values = _energy_values(cell.runs)
    latency_values = _latency_values(cell.runs)
    if not energy_values or not latency_values:
        raise ValueError(f"cell has no accepted values: {cell.task}/{cell.target}")
    energy_p50 = statistics.median(energy_values)
    latency_p50 = statistics.median(latency_values)
    energy_cv = _cv(energy_values)
    latency_cv = _cv(latency_values)
    energy_band_fraction = max(3.0 * energy_cv, floor)
    latency_band_fraction = max(3.0 * latency_cv, floor)
    energy_cv_text = _format_cv(energy_cv)
    if cell.task == "ad" and cell.target == "esp32s3" and energy_cv > floor:
        energy_cv_text = "see caveat"
        energy_band_fraction = floor
    return (
        f"| {cell.task.upper()} | {_board_label(cell.target)} | "
        f"{energy_p50:.3f} | {energy_cv_text} | {_band(energy_p50, energy_band_fraction)} | "
        f"{latency_p50:.3f} | {_format_cv(latency_cv)} | {_band(latency_p50, latency_band_fraction)} |"
    )


def _energy_values(runs: Sequence[RunData]) -> list[float]:
    return [
        float(run.energy_stats["wh_per_1000"]) * 1000.0
        for run in runs
        if run.energy_stats is not None
        and not run.telemetry_partial
        and not repeat_quarantined(run)
    ]


def _latency_values(runs: Sequence[RunData]) -> list[float]:
    return [
        float(run.latency_stats["median_us"]) / 1000.0
        for run in runs
        if run.latency_stats is not None
        and not run.telemetry_partial
        and not repeat_quarantined(run)
    ]


def _cv(values: Sequence[float]) -> float:
    if len(values) <= 1:
        return 0.0
    return float(statistics.stdev(values) / statistics.fmean(values))


def _format_cv(value: float) -> str:
    pct = value * 100.0
    if pct < 0.1:
        return f"{pct:.3f}%"
    return f"{pct:.2f}%"


def _band(center: float, fraction: float) -> str:
    return f"{center * (1.0 - fraction):.3f}-{center * (1.0 + fraction):.3f}"


def _board_label(target: str) -> str:
    return {
        "f401re": "F401RE",
        "nano33": "Nano 33",
        "esp32s3": "ESP32-S3",
    }[target]


def _display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def _db_source_label(path: Path) -> str:
    if path.name in {"p3_mcu_matrix.db", "p3_mcu_matrix.sanitized.sqlite"}:
        return "Post 1 telemetry SQLite database"
    return _display_path(path)


if __name__ == "__main__":
    raise SystemExit(main())
